# Generated by Django 5.0.7 on 2024-09-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
