# Generated by Django 5.0.7 on 2024-10-05 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
