# Generated by Django 5.0.7 on 2024-09-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('home', 'home'), ('Kids', 'Kids'), ('Baby', 'Baby'), ('Sports', 'Sports')], default='men', max_length=10),
        ),
    ]
